### ISSUE TITLE
Conflict with latest Liberty Tweaks

### ISSUE THREAD

**Issue by Ex3cutionerX** [ClonkAndre/IV-SDK-DotNet#28]
Here's the log: 
[08/12/2024 09:04:02] IV-SDK .NET Release version 1.8 by ItsClonkAndre
[08/12/2024 09:04:02] Loaded IV-SDK .NET config.ini!
[08/12/2024 09:04:05] Finished loading 0 IV-SDK .NET Manager Plugin(s).
[08/12/2024 09:04:06] Found script: LibertyTweaks.Main
[08/12/2024 09:04:06] Found script: ProjectThunderIV.Main
[08/12/2024 09:04:06] [ProjectThunderIV] Loaded 4 sound configurations!
[08/12/2024 09:04:06] [ProjectThunderIV] Loaded 2 electrical substation positions!
[08/12/2024 09:04:06] [ProjectThunderIV] Loaded 6 scripted lightnings!
[08/12/2024 09:04:06] Finished loading 2 IV-SDK .NET script(s).
[08/12/2024 09:04:41] There is currently no new IV-SDK .NET update available.
[08/12/2024 09:04:43] An error occured while processing 'GameLoadPriority' event for IV-SDK .NET script 'LibertyTweaks.Main'. Aborting. Error details available below.
[08/12/2024 09:04:43] Possible Solution: Make sure the MOD itself, its DEPENDENCIES and IV-SDK .NET is up-to-date.
[08/12/2024 09:04:43] Details: System.MissingMethodException: Method not found: 'Void IVSDKDotNet.IVCDStream.AddImage(System.String, Byte, Int32)'.
   at LibertyTweaks.ArmoredCops.LoadFiles()
   at LibertyTweaks.Main.Main_GameLoadPriority(Object sender, EventArgs e)
   at IVSDKDotNet.Script.RaiseGameLoadPriority()
   at Manager.Classes.FoundScript.RaiseGameLoadPriority()
   at Manager.Main.<RaiseGameLoadPriority>b__42_0(FoundScript fs)
[08/12/2024 09:04:43] Aborting script LibertyTweaks.Main...
[08/12/2024 09:04:43] Manager successfully aborted script LibertyTweaks.Main.
[08/12/2024 09:04:51] Found ScriptHookDotNet script: ArrestWarrant.Main
[08/12/2024 09:04:51] Finished loading 1 ScriptHookDotNet script(s).
[08/12/2024 09:17:26] Application is closing, starting cleanup process...
[08/12/2024 09:17:26] Cleanup process finished!

**Comment by GXTVV** [comment]
Try downgrading IV-SDK .NET to 1.7 and if you are using LibertyTweaks 1.6, downgrade to 1.5!

**Comment by ClonkAndre** [comment]
> Possible Solution: Make sure the MOD itself, its DEPENDENCIES and IV-SDK .NET is up-to-date.
Liberty Tweaks needs to be updated to work with IV-SDK .NET v1.8

**Comment by Ex3cutionerX** [comment]
> > Possible Solution: Make sure the MOD itself, its DEPENDENCIES and IV-SDK .NET is up-to-date.
> 
> Liberty Tweaks needs to be updated to work with IV-SDK .NET v1.8

It's working great now with the new Libertytweaks 1.6 update fix.
